---
title: "webscraping_dog_breed_popularity"
author: "Kristen A, kkakey"
date: "12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(tidyverse)
```


Script to retrieve popularity rankings (2013 - 2020)
- https://www.akc.org/most-popular-breeds/

```{r}
full_df <- data.frame(matrix(ncol = 2, nrow = 0))
for (year in seq(2013,2020)) {
  page <- paste0("https://www.akc.org/most-popular-breeds/",year,"-full-list/")
  
  if (year==2020) {
    page <- "https://www.akc.org/expert-advice/dog-breeds/the-most-popular-dog-breeds-of-2020/"
  }

  breed_rank_past <- read_html(page) %>%
    html_nodes("div.page-layout") %>%
    html_nodes("div.article-body") %>%
    html_table(fill = TRUE) %>%
    as.data.frame() %>%
    janitor::row_to_names(row_number=1) %>%
    # fix UTF-8 encoding, affects 2020
    mutate_at(vars(Breed), function(x){gsub('[^ -~]', ' ', x)}) %>%
    rename_at(vars(starts_with("Rank")), funs(paste0(year, ' ', .)))
  
  if (year!=2013) {
    full_df <- full_df %>%
      left_join(.,breed_rank_past, on="Breed")
  } else {
    full_df <- rbind(full_df, breed_rank_past)
  }

}
```

```{r}
# Add links and images to the dataset that were retrieved with webscraping_script-1.Rmd
breed_rank_2020 <- read.csv("./data/table_rank_2020.csv") %>%
  select(!X2020.Rank) %>%
  # fix UTF-8 encoding
  mutate_at(vars(Breed), function(x){gsub('[^ -~]', ' ', x)}) 

image_links_df <- read.csv("./data/breed_weight_image.csv") %>%
  select(!Weight) %>%
  # fix UTF-8 encoding
  mutate_at(vars(Breed), function(x){gsub('[^ -~]', ' ', x)}) 

breed_rank <- full_df %>%
  left_join(., breed_rank_2020, on="Breed") %>%
  left_join(., image_links_df, on="Breed")
```

```{r}
write.csv(breed_rank, "./data/breed_rank_all.csv", row.names = F)
saveRDS(breed_rank, "./data/breed_rank_all.rds")
```

